#!/bin/bash

echo "======================================"
echo "Manual GitHub Repository Setup"
echo "======================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to: https://github.com/new"
echo "   - Repository name: framer-rive-assets"
echo "   - Description: Rive animation files for Framer projects"
echo "   - Make it PUBLIC (important for GitHub Pages)"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "cd /Users/adebimpeomolaso/Projects/riv-framer/framer-rive-assets"
echo "git remote add origin https://github.com/adshine/framer-rive-assets.git"
echo "git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to: https://github.com/adshine/framer-rive-assets/settings/pages"
echo "   - Under 'Source', select 'Deploy from a branch'"
echo "   - Under 'Branch', select 'main' and '/ (root)'"
echo "   - Click 'Save'"
echo ""
echo "4. Wait 2-3 minutes for GitHub Pages to deploy"
echo ""
echo "5. Your files will be available at:"
echo "   - https://adshine.github.io/framer-rive-assets/radmulti.riv"
echo "   - https://adshine.github.io/framer-rive-assets/radsingle.riv"
echo "   - https://adshine.github.io/framer-rive-assets/rotation.riv"
echo "   - https://adshine.github.io/framer-rive-assets/stroke.riv"
echo ""
echo "======================================"